import type { Metadata } from "next";
import "./globals.css";

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { getServerSession } from "next-auth";
import SessionProvider from "@/utils/SessionProviders";

export const metadata: Metadata = {
  title: "k37: ADITYA",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className="">
        <SessionProvider session={session}>
          <Navbar />
          <div className="child">{children}</div>
          <Footer />
        </SessionProvider>
      </body>
    </html>
  );
}
